### ISSUE TITLE
custom samplers

### ISSUE THREAD

**Issue by brettmc** [open-telemetry/opentelemetry-configuration#102]
The file-configuration schema allows for extra properties in the `sampler`, allowing me to define a sampler other than the ones defined in spec.

I'm in the process of implementing a rule-based sampler, based on Java's implementation. I foresee a collision in the future where Java SIG will also want to add and configure a rule-based sampler, and it probably won't have the same schema.

How can we support the configuration of custom/non-spec-defined samplers such that we can coexist with future samplers?

For reference, an example of our custom rule-based sampler configuration:

```yaml
tracer_provider:
  sampler:
    rule_based:
      rule_sets:
        - rules:
            - attribute: {key: is.important, pattern: ~false~ }
          delegate:
            always_off: {}
        - rules:
            - link: { sampled: true }
          delegate:
            always_on: {}
        - rules:
            - span_name: { pattern: ~foobar~ }
          delegate:
            always_off: {}
        - rules:
            - span_kind: { kind: SERVER }
            - attribute: { key: url.path, pattern: ~^/health$~ }
          delegate:
            always_off: {}
      fallback:
        always_on: {}
```
The sampler runs through rules until it finds a match, and then delegates the decision to the configured sampler for that rule. If no match, fall back to a different sampler.
