### ISSUE TITLE
[EXAMPLES] Periodic exporter interval default value is inconsistent.

### ISSUE THREAD

**Issue by marcalff** [open-telemetry/opentelemetry-configuration#108]
The examples reads as:

```
    # Configure a periodic metric reader.
    - periodic:
        # Configure delay interval (in milliseconds) between start of two consecutive exports.
        #
        # Environment variable: OTEL_METRIC_EXPORT_INTERVAL
        interval: 5000
        # Configure maximum allowed time (in milliseconds) to export data.
        #
        # Environment variable: OTEL_METRIC_EXPORT_TIMEOUT
        timeout: 30000
```

Per the spec:

* https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/configuration/sdk-environment-variables.md#periodic-exporting-metricreader

the default value for `interval` is 60000.

The problem here is not so much the values used (examples are free to use anything), but the fact that this setup is invalid, at least for opentelemetry-cpp:

* the C++ SDK enforces that `timeout` < `interval`

Since every other numerical value provided in examples seem to match defaults, please consider to use the default (60000) for `interval`, to avoid confusion.

Currently:

```
[malff@malff-desktop examples]$ grep "interval:" *
anchors.yaml:        interval: 5000
kitchen-sink.yaml:        interval: 5000
sdk-config.yaml:        interval: 60000
sdk-migration-config.yaml:        interval: ${OTEL_METRIC_EXPORT_INTERVAL:-60000}
```

Files `anchors.yaml` and `kitchen-sink.yaml` use 5000 instead.
