### ISSUE TITLE
Consider renaming OTLP certificate properties

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/opentelemetry-configuration#160]
Example OTLP exporter config:

```
tracer_provider:
  processors:
    - batch:
        exporter:
          otlp_http:
            endpoint: http://localhost:4318/v1/traces
            # Configure certificate. 
            # Absolute path to certificate file.
            # If omitted or null, system default certificate verification is used for secure connections.
            certificate: /app/cert.pem
            # Configure mTLS private client key. 
            # Absolute path to client key in PEM format. If set, .client_certificate must also be set.
            # If omitted or null, mTLS is not used.
            client_key: /app/cert.pem
            # Configure mTLS client certificate. 
            # Absolute path to certificate file. If set, .client_key must also be set.
            # If omitted or null, mTLS is not used.
            client_certificate: /app/cert.pem
```

Right now, fact that properties values are supposed to be the absolute path to files is reflected in the property description, but this has bothered me for a while as its not intuitive that I can't directly put a PEM file's contents in the property.

We should consider adding a `*_file` or `*_path` suffix to these properties, making the semantics self describing. I.e.:

```
tracer_provider:
  processors:
    - batch:
        exporter:
          otlp_http:
            endpoint: http://localhost:4318/v1/traces
            certificate_file: /app/cert.pem
            client_key_file: /app/cert.pem
            client_certificate_file: /app/cert.pem
```
