### ISSUE TITLE
OTEL_RESOURCE_ATTRIBUTES with variable type array

### ISSUE THREAD

**Issue by adelbot** [open-telemetry/opentelemetry-configuration#177]
How use the env variable OTEL_RESOURCE_ATTRIBUTES to defined one variable that is arrat type ?

 OTEL_RESOURCE_ATTRIBUTES=service.name=shoppingcard,will_be_overridden=foo,w00.targets=["wbk","ade"] is KO

Have you any idea ?

**Comment by brettmc** [comment]
Hi @adelbot I don't think that will work, and I am not sure whether it should. https://opentelemetry.io/docs/specs/otel/resource/sdk/#specifying-resource-information-via-an-environment-variable only specifies that key-value pairs are accepted through OTEL_RESOURCE_ATTRIBUTES.
There is a sub-project underway to specify declarative config, which allows for much richer configuration than is possible through env vars, and it looks like that one does allow for arrays: https://github.com/open-telemetry/opentelemetry-configuration/blob/v0.3.0/schema/resource.json#L24

**Comment by jack-berg** [comment]
Hey @adelbot - yes @brettmc is correct. Its not possible to encode non-string type attributes via `OTEL_RESOURCE_ATTRIBUTES`. See issue here: https://github.com/open-telemetry/opentelemetry-specification/issues/2857

This is actually one of the motivations behind the [declarative config project](https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/configuration#declarative-configuration). Without the limits of env vars, we can allow users to specify resource attributes of all types. In your case, this would look like:

```
resource:
  attributes:
    - name: service.name
       value: shopppingcard
    - name: will_be_overridden
       value: foo
    - name: w00.targets
       type: string_array
       value:
         - wbk
         - ade
```

Closing this issue since this is already a solved problem in declarative config and won't be solved with `OTEL_RESOURCE_ATTRIBUTES`.
