### ISSUE TITLE
metric_readers section name could be shortened to readers

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-configuration#20]
### TL;DR

The `metric_readers` section can be shortened to `readers` which would be shorter while still being readable and concrete enough, and would make the OpenTelemetry Collector telemetry configuration cleaner.

### Longer explanation & context

On open-telemetry/opentelemetry-collector/pull/7871 we are using the Configuration WG's `meter_provider` configuration schema as part of the OpenTelemetry Collector telemetry configuration. In this case, configuring a reader looks like the following:

```yaml
# collector.yaml sample telemetry configuration
service:
  telemetry:
    metrics:
      metric_readers:
        pull/prometheus:
          # ...
```

As noted, this matches the example on this repository:

https://github.com/open-telemetry/opentelemetry-configuration/blob/362b23ec9bb61537e6479a9546d7e8f8a388ec81/kitchen-sink-example.yaml#L64-L69

Although I believe in our case it is specially more salient because our top level configuration is named `metrics`, I still think on the base example on this repository the `metric_` prefix for the `metric_readers` subsection is redundant: a meter provider will presumably never have any other kind of reader.
