### ISSUE TITLE
Add IdGenerator in the trace_provider

### ISSUE THREAD

**Issue by marcalff** [open-telemetry/opentelemetry-configuration#70]
The specification defines IdGenerator as an extension point:

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#id-generators

The yaml for `tracer_provider:` should probably allow to define which id generator to use, something like:

```
tracer_provider:
  id_generator:
    # SDK extension point
    my_custom_id_generator:
```

Found while prototyping for opentelemetry-cpp
