### ISSUE TITLE
Add mementos to facilitate post processing the configuration model

### ISSUE THREAD

**Issue by marcalff** [open-telemetry/opentelemetry-configuration#73]
Some context to explain the problem:

Assume a yaml document like:

```
some:
  path:
   to:
    exporter:
      otlp:
        endpoint: "..."

another:
  path:
   to:
    exporter:
      otlp:
        endpoint: "..."
```

After parsing this yaml file, the result is a `ConfigurationModel` tree.

This tree contains two nodes, `OtlpConfigurationModel`.

When the main code, in the application, wants to process this model after parsing, to make adjustments:

* Applying the **_same_** change to all instances (say, set `insecure=false`) for every `OtlpConfigurationModel` node, is possible.
* Applying a **_different_** change to different instances (say, set `client_cert` differently) for every `OtlpConfigurationModel` node, is not possible.

The problem is that the code has no context to differentiate instances.

The proposed solution is to add an optional string `memento` property in each node.

Think of a memento as a post-it attached to a node, in yaml.

```
some:
  path:
   to:
    exporter:
      otlp:
        memento: "blue"
        endpoint: "..."

another:
  path:
   to:
    exporter:
      otlp:
        memento: "green"
        endpoint: "..."
```

When post processing `OtlpConfigurationModel` instances, the application code can:

* set `client_cert` = `blue_cert.pem` for blue nodes
* set `client_cert` = `green_cert.pem` for green nodes

because the code can read the memento property to guide post processing.
