### ISSUE TITLE
add support for instrumentation configuration?

### ISSUE THREAD

**Issue by brettmc** [open-telemetry/opentelemetry-configuration#87]
Over in PHP SIG, we've started to implement file-based configuration, and it's going well.
We also have a requirement where some of our automatic instrumentation modules require configuration. So, following the file-configuration way of thinking, we're enabling this through a secondary .yaml file, along with another env var to point to the file. For example, `OTEL_PHP_INSTRUMENTATION_CONFIG_FILE=otel-instrumentation.yaml`:
```yaml
config:
  - example_instrumentation:
      span_name: ${EXAMPLE_INSTRUMENTATION_SPAN_NAME:-example span}
  - another_instrumentation:
      enabled: false
      foo_param: "some.value"
```

Could something like this be incorporated into the SDK configuration schema, for example under an `instrumentation` key?
